Repository citation-style-language/styles, pull requests merged in 2021-11, with the labels that each got.

#5662 wikipedia generic citation
  wikipedia-templates.csl
Labels: style-submission

#5673 Create tyndale-bulletin-fullnote-bibliography
  tyndale-bulletin.csl
Labels: style-submission, waiting-for-response-from-contributor

#5685 Create the-angle-orthodontist.csl
  the-angle-orthodontist.csl
Labels: waiting-for-response-from-contributor

#5643 Update harvard-imperial-college-london.csl
  harvard-imperial-college-london.csl
Labels: waiting-for-response-from-contributor

#5641 Update vancouver-imperial-college-london.csl
  vancouver-imperial-college-london.csl
Labels: waiting-for-response-from-contributor

#5699 Create forschungsjournal-soziale-bewegungen-fjsb.csl
  forschungsjournal-soziale-bewegungen-fjsb.csl
Labels: style-submission

#5559 Update mohr-siebeck-recht.csl
  mohr-siebeck-recht.csl
Labels: waiting-for-response-from-contributor
